#!/usr/bin/env python3
"""
Load CoreTerra config and output environment variables for shell sourcing.

Usage:
    eval $(uv run python backend/scripts/load_env.py)

This script reads ~/.coreterra/config.json and outputs environment variables
that can be sourced by the shell before starting the servers.

It also generates a .env file in the frontend directory for Vite to read.
"""

import json
import sys
from pathlib import Path


def load_config() -> dict:
    """Load configuration from ~/.coreterra/config.json with defaults."""
    config_path = Path.home() / ".coreterra" / "config.json"

    defaults = {
        "user_id": "00000000-0000-0000-0000-000000000001",
        "api_url": "http://localhost:8000",
        "frontend_url": "http://localhost:5173",
    }

    if config_path.exists():
        try:
            with open(config_path) as f:
                config = json.load(f)
                defaults.update(config)
        except json.JSONDecodeError as e:
            print(f"Warning: Invalid JSON in {config_path}: {e}", file=sys.stderr)
            print("Using default configuration.", file=sys.stderr)

    return defaults


def write_frontend_env(config: dict, project_root: Path) -> None:
    """Write .env file for Vite frontend."""
    frontend_env_path = project_root / "frontend" / ".env"

    env_content = f"""# Auto-generated by load_env.py - DO NOT EDIT MANUALLY
VITE_API_URL={config.get("api_url", "http://localhost:8000")}
VITE_USER_ID={config.get("user_id", "")}
"""

    with open(frontend_env_path, "w") as f:
        f.write(env_content)


def main() -> None:
    """Output environment variables for shell sourcing and generate .env file."""
    config = load_config()

    # Determine project root (script is in backend/scripts/)
    script_path = Path(__file__).resolve()
    project_root = script_path.parent.parent.parent

    # Generate .env file for Vite
    write_frontend_env(config, project_root)

    # Output for backend (shell export)
    print(f'export CORETERRA_USER_ID="{config.get("user_id", "")}"')
    print(
        f'export CORETERRA_API_URL="{config.get("api_url", "http://localhost:8000")}"'
    )

    # Output for frontend (Vite requires VITE_ prefix)
    print(f'export VITE_API_URL="{config.get("api_url", "http://localhost:8000")}"')
    print(f'export VITE_USER_ID="{config.get("user_id", "")}"')


if __name__ == "__main__":
    main()
